### ISSUE TITLE
building on Mac M2 arch

### ISSUE THREAD

**Issue by mnfienen** [pypest/pypestutils#16]
@mwtoews - I hope there is a reasonably simple answer, but following the https://github.com/pypest/pypestutils/blob/main/BUILD.md instructions, I installed meson and ninja via pip and already have gfortran available at the commandline. When I run the build libs script, however, I get an error about not being able to find GNU compiler. Top of the error is like this:
<img width="441" alt="image" src="https://github.com/pypest/pypestutils/assets/1110827/f3576d74-56e0-4877-80fc-4b365c15eb40">
and after all the `#defines` I see this
<img width="480" alt="image" src="https://github.com/pypest/pypestutils/assets/1110827/2ea4c517-6f08-4b85-9f70-42449e1fb3b6">
I'm on OS 13.6. Does this ring any bells?

**Comment by mnfienen** [comment]
thanks @mwtoews I tried reinstalling XCode CLtools but still same error.....

**Comment by mwtoews** [comment]
Bummer! Is your set-up able to compile other gcc/gfortran projects with meson such as mf6, or is it only having difficulty with pestutils? Is it via homebrew's [gcc](https://formulae.brew.sh/formula/gcc)? What version does `gfortran --version` show? @briochh might have ideas, as he has a macOS silicone laptop (I don't).

**Comment by mnfienen** [comment]
hmmmm..... no - I haven't compiled anything in a bit.

version is GNU Fortran (GCC) 12.1.0

I'll see if @briochh sees the bat signal :). Thanks!

**Comment by briochh** [comment]
I see it, but I may not be much help. I am sans computer for the next months. The only thing I remember is that I could only compile using a true python version (i.e. not conda python).
Also I don't think i used meson, i think I was running cibuildwheel ...

**Comment by briochh** [comment]
@mnfienen, @mwtoews has put together some steps for building on Mac running arm. I have just work through on my M1 machine to upload arm wheels to pypi. You could see if it also works on M2? 
https://github.com/pypest/pypestutils/wiki/BuildingBdistForMacOSarm64

**Comment by mnfienen** [comment]
I'm actually still on M1 Max I figured out. But....I found that by  `mamba` installing `gfortran` from `conda-forge` into the same env as `meson` and `ninja` everything just worked fine

**Comment by mwtoews** [comment]
Updates to https://github.com/pypest/pypestutils/blob/main/BUILD.md are always welcome! Perhaps more conda-specific instructions should be there? (Currently it's primarily conda for Windows)

**Comment by mnfienen** [comment]
great idea - I'll PR some instructions
