### ISSUE TITLE
pip install failing on MacOS

### ISSUE THREAD

**Issue by mnfienen** [pypest/pypestutils#34]
I was able to `pip` install `pypestutils` a while back but just tried again fresh in a new env and it's not working. No errors on install, but it appears the compiled libraries are not being installed. 

This snippet:
```
from pypestutils.pestutilslib import PestUtilsLib  
lib = PestUtilsLib() #the constructor searches for the shared lib
```

results in this error:
![image](https://github.com/user-attachments/assets/20c80670-f62d-4336-a4c8-5d5c95f54600)

Keen to know what I could do differently

**Comment by mwtoews** [comment]
Which version is this? I believe I've set-up native macOS Silicon wheel building via GHA, but I haven't released this version to pip yet.

You can try going to [a latest wheel build](https://github.com/pypest/pypestutils/actions/runs/10956202914) then scroll down to the "Artefacts" section and download "cibw-wheels-macos-14-arm64" unzip it then:

    pip install ./pypestutils-0.2.1.dev0-py3-none-macosx_14_0_arm64.whl

I think the only reason why I haven't released the latest version is that I'm caught up with the git-flow release steps between "develop" and "main" branches, which is different than other packages that I manage.

**Comment by mnfienen** [comment]
Thanks @mwtoews ! That did it!
