### ISSUE TITLE
get_modflow() issues in the tests

### ISSUE THREAD

**Issue by jtwhite79** [pypest/pypestutils#35]
[https://github.com/pypest/pypestutils/actions/runs/11140750010](https://github.com/pypest/pypestutils/actions/runs/11140750010)

We are failing lots of tests (on pyemu and pestpp also) related to this issue.  @mwtoews is there a quick work around we can use to patch?

**Comment by mwtoews** [comment]
This is fixed via https://github.com/modflowpy/flopy/pull/2320, so perhaps a band-aid fix until the next flopy release is to depend on the latest develop branch?

**Comment by jtwhite79** [comment]
Didn't realize this had already been addressed.  Thanks @mwtoews

**Comment by mwtoews** [comment]
A latest flopy with a fix was just released.
